#!/bin/bash
unset kernelrelease kernelentrynumber initramfs

version='0.1'

workdir="$(pwd)"

# A dummy function to prevent people from using lazykernel before they edit /etc/lazykernel.conf
CONFIGUREFIRST() {
	echo "First you need to edit /etc/lazykernel.conf."
	exit 1
}

if [ -r /etc/lazykernel.conf ]; then
	. /etc/lazykernel.conf
else
	echo "Missing /etc/lazykernel.conf"
	exit 1
fi

einfo() { echo -e "\033[1;32m>>> \033[0m$@"; }
eerror() { echo -e "\033[1;31m>>> \033[0m$@" >&2; }
wat() { einfo "${FUNCNAME[1]}() ..."; }

check_kernel_sources() {
	if ! [ -f "${workdir}/Kbuild" ] || ! [ -f "${workdir}/Makefile" ]; then
		eerror "The \"${workdir}/\" does not contain kernel sources, propably."
		exit 1
	fi
}

get_kernel_release() {
	if [ -z "${kernelrelease}" ]; then
		kernelrelease="$(make kernelrelease)"
	fi
}

deploy() {
	wat
	check_kernel_sources
	get_kernel_release
	if ! [ -f 'arch/x86/boot/bzImage' ]; then
		eerror "there is no bzImage."
		exit 1
	fi

	einfo "Deploying '${kernelrelease}' ..."

	make modules_install
	depmod -qa
	cp arch/x86/boot/bzImage "/boot/bzImage-${kernelrelease}"
}

list() {
	get_kernels_versions
}

get_kernels_versions() {
	shopt -s nullglob
	if [ -z "${sort_by}" ]; then sort_by='mtime'; fi
	if [ "${sort_by}" = 'version' ]; then
		for bzImage in $(sort -r --version-sort < <(printf '%s\n' /boot/bzImage-*)); do
			echo "${bzImage##/boot/bzImage-}"
		done
	elif [ "${sort_by}" = 'mtime' ]; then
		for bzImage in $(ls -t /boot/bzImage-*); do
			echo "${bzImage##/boot/bzImage-}"
		done
	else
		eerror 'Wrong sort_by variable.'
		exit 1
	fi
	shopt -u nullglob
}

clean() {
	wat
	bzImages=( $(get_kernels_versions) )
	if [ -z "${keep_kernels}" ]; then keep_kernels='3'; fi
	kernels_to_remove=( ${bzImages[@]:${keep_kernels}} )

	if [ "${#kernels_to_remove[@]}" = 0 ]; then
		einfo "Nothing to remove."
		return
	fi

	einfo 'The following kernels will be removed:'
	printf '\t%s\n' "${kernels_to_remove[@]}"

	local answer
	echo -n "Sure you want to remove all those kernels? [yN] "
	read -n 1 answer
	echo
	if ! [[ "${answer}" =~ ^[yY]$ ]]; then return 1; fi

	remove_kernel "${kernels_to_remove[@]}"
}

gen-extlinuxconf() {
	wat
	kernels=( $(get_kernels_versions) )
	if [ "${#kernels[@]}" -lt '1' ]; then
		eerror "No kernel images?"
		return 1
	fi
	test -f /boot/extlinux/extlinux.conf && cp /boot/extlinux/extlinux.conf /boot/extlinux/extlinux.conf.old
	shopt -s nullglob
	(
		echo "# This configuration file was generated automatically by gen-extlinuxconf.

TIMEOUT 30
UI menu.c32

MENU TITLE Boot Menu
MENU COLOR title	1;37;40
MENU COLOR border	30;40
MENU COLOR unsel	37;40
"

		if [ "$(stat -c '%d' '/')" = "$(stat -c '%d' '/boot')" ]; then
			bootdir='/boot'
		else
			bootdir=''
		fi
		
		for bzImage_ver in "${kernels[@]}"; do
			kernelentrynumber="${kernelentrynumber:-1}"
			echo "LABEL kernel${kernelentrynumber}_bzImage-${bzImage_ver}"
			echo "	MENU LABEL ${menu_entry_name} bzImage-${bzImage_ver}"
			echo "	LINUX ${bootdir}/bzImage-${bzImage_ver}"
			if [ -n "${initramfs}" ] && [ -f "/boot/${initramfs}" ]; then
				echo "	INITRD ${bootdir}/${initramfs}"
			fi
			if [ "${initramfs_per_kernel}" = 'true' ] && [ -f "/boot/initramfs-${bzImage_ver}" ]; then
				echo "	INITRD ${bootdir}/initramfs-${bzImage_ver}"
			fi
			if [ -n "${kernel_params}" ]; then
				echo "	APPEND ${kernel_params}"
			fi

			kernelentrynumber="$((kernelentrynumber+1))"
			echo
		done

		# If there is memdisk and disk images, add them to menu as well. useful for example for freedos images to update BIOS etc.
		if [ -f '/boot/extlinux/memdisk' ]; then
			for diskimage in /boot/*.iso /boot/*.img; do
				# Skip images with initrd or initramfs prefix.
				if [[ "${diskimage##*/}" =~ ^initrd.*$ ]] || [[ "${diskimage##*/}" =~ ^initramfs.*$ ]]; then continue; fi
				memdiskentrynumber=${memdiskentrynumber:-1}
				imagesize="$(($(stat -c '%s' "${diskimage}")/1024/1024))"
				echo "LABEL memdisk${memdiskentrynumber}_${diskimage##*/}"
				echo "	MENU LABEL Boot image: '${diskimage##*/}' (${imagesize} MB)"
				echo "	LINUX memdisk"
				echo "	INITRD ${bootdir}/${diskimage##*/}"
				if [[ "${diskimage##*/}" =~ ^.*.iso$ ]]; then
					echo "	APPEND iso"
				elif [[ "${diskimage##*/}" =~ ^.*.img$ ]]; then
					echo "	APPEND raw"
				fi
				memdiskentrynumber="$((memdiskentrynumber+1))"
				echo
			done
		fi
	) > /boot/extlinux/extlinux.conf
	shopt -u nullglob
	printf '    * %s\n' "${kernels[@]}"
}

remove_kernel() {
	wat
	for kernel in "$@"; do
		if [ -f "/boot/bzImage-${kernel}" ]; then
			echo ">>> Removing /boot/bzImage-${kernel} ..."
			rm -f "/boot/bzImage-${kernel}"
		fi
		if [ -d "/lib/modules/${kernel}" ]; then
			echo ">>> Removing /lib/modules/${kernel}/ ..."
			rm -rf "/lib/modules/${kernel}/"
		fi
	done
}

help() {
cat <<EOF
${0##*/} v${version}

	Options:
	deploy - copy bzImage to /boot/bzImage-<kernel-version> and run make modules_install.
	clean - Try to remove old kernel images if there is more than keep_kernels parametr from config.
	list - list kernels from /boot.
	remove_kernel <version> - remove kernel <version>
	gen-extlinuxconf - regenerate /boot/extlinux/extlinux.conf
	auto - also known as 'ultra lazy mode', run deploy, clean and gen-extlinuxconf.

2012 (c) Piotr Karbowski <piotr.karbowski@gmail.com>
Work smart not hard.

EOF
}

case "$1" in
	list|deploy|clean|remove_kernel|gen-extlinuxconf)
		"$1" "${@:2}"
	;;
	auto)
		deploy
		clean
		gen-extlinuxconf
	;;
	*)
		help
		exit 1
	;;
esac
